#!/bin/bash

# First set the environment variables
source /etc/novarc

# Kick-off the OpenStack services
service nova-api start
service nova-scheduler start
service keystone start
service quantum-l3-agent start
service quantum-dhcp-agent start
service quantum-plugin-openvswitch-agent start
service rabbitmq-server start
service mysql start
service openvswitch-switch start

# Invoke glance to install the VM images
for f in `ls /etc/gram_images/*.img`
do
    glance image-create --name=$f --disk-format=qcow2 --container-format=ovf --is-public=True < $f
done

# Create link in gcf installation directory
cd /opt
ln -s gcf-2.2 gcf

# Update .barshrc file in new gram user account
echo "source /etc/novarc" >> /home/gram/.bashrc
echo 'export PATH=/home/gram/gram/src:/opt/gcf/src:$PATH' >> /home/gram/.bashrc
echo 'export PYTHONPATH=/opt/gcf/src:/home/gram/gram/src' >> /home/gram/.bashrc

# Make sure /etc/gram is corect permissions
chmod 777 /etc/gram

# Install GRAM source
cd /home/gram
mkdir -p .gcf
cp gram/gcf_config .gcf
cp -r /etc/gram/certs/* .gcf
chown gram.root gram
chown -R gram.root .gcf
chown -R gram.root /etc/gram

# Install GRAM services
cd /home/gram/gram/src/services
for svc in gram-am gram-amv2
do
    sed -i "s/env OS_USERNAME.*/env OS_USERNAME=$OS_USERNAME/" $svc.conf
    sed -i "s/env OS_TENANT_NAME.*/env OS_TENANT_NAME=$OS_TENANT_NAME/" $svc.conf
    sed -i "s/env OS_PASSWORD.*/env OS_PASSWORD=$OS_PASSWORD/" $svc.conf
    sed -i "s/env SERVICE_TOKEN.*/env SERVICE_TOKEN=$SERVICE_TOKEN/" $svc.conf
done
cp *.conf /etc/init
cd /etc/init.d
for svc in gram-am gram-amv2 gram-cni gram-ch  gram-ctrl gram-vmoc 
do
    ln -s /lib/init/upstart-job $svc
    service $svc start
done

# Install the gram ssh proxy
cd /home/gram/gram/src/gram/am/gram
make 

# Create omniuser account
useradd -m -s /bin/bash omniuser
adduser omniuser sudo
passwd omniuser
mkdir -p /home/omniuser/.ssh
chown omniuser.omniuser /home/omniuser/.ssh

# Add GCF paths to omniuser .basrc file
echo '' > /home/omniuser/.bashrc
echo 'export PATH=/opt/gcf/src:$PATH' >> /home/omniuser/.bashrc
echo 'export PYTHONPATH=/opt/gcf/src' >> /home/omniuser/.bashrc
echo 'source /etc/novarc' >> /home/omniuser/.bashrc

# Start with default omni_config file
# Install clearinghouse and AM certs in omniuser .gcf directory
mkdir -p /home/omniuser/.gcf
cd /home/omniuser/.gcf
cp /home/gram/gram/omni_config .
cp /etc/gram/certs/*.pem .
chown omniuser *


